Algoritmo "Mediana"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Marcelo
// Descrição   : Faz a Mediana dos Valores.
// Autor(a)    : Lucca e Yara
// Data atual  : 06/09/2023
Var
   A, B: Inteiro
   Media: Real
Inicio
      Escreval ("Digite um valor: ")
      Leia (A)
      Escreval ("Digite outro valor: ")
      Leia (B)
      
      Media <- (A+B)/2

      Escreval ("Esta é a media dos valores: ", Media)
Fimalgoritmo